[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "pytest>=8.4.2",
    "sqlmodel>=0.0.25",
    "tzdata>=2025.2",
]
